### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by orangemug** [maputnik/maputnik.github.io#1]
I think maputnik deserves a new homepage, showing it off a little more. I'm raising this ticket to start the discussion.

Here's what I think it should have

 - A big screenshot showing off the app
   - Later maybe a https://github.com/runkitdev/demokit video, something simple that's easy to keep up to date as the app changes.
 - Features, showing why should people use it.
 - Show off some existing open source styles which people can modify as an easy starting point.

**Comment by orangemug** [comment]
Here is my first attempt https://orangemug.github.io/maputnik-web-mockup let me know what you think...

**Comment by orangemug** [comment]
@lukasmartinelli is there a SVG version of this file https://github.com/maputnik/editor/blob/master/src/img/maputnik.png somewhere, or was it always png?

**Comment by lukasmartinelli** [comment]
> Here is my first attempt https://orangemug.github.io/maputnik-web-mockup let me know what you think...

You are a genius. I love this!!
Please go for that in `maputnik/website`.

Please also add yourself as maintainer and give yourself credit somewhere on the homepage!!

> @lukasmartinelli is there a SVG version of this file https://github.com/maputnik/editor/blob/master/src/img/maputnik.png somewhere, or was it always png?

It was always a PNG but I can dig up a very high resolution PNG I used for the laptop stickers if you want to.

If you have a great idea for a better logo you can also do it (in the style of the website).
I am happy with the current logo - but it is obviously not professional.

**Comment by orangemug** [comment]
Yeah the high res version would be great, maybe just create a `maputnik/design` repo for the logos / assets. I'll probably generate a SVG version as well as a black/white version.

Also I really like the current logo, so lets stick with that.

**Comment by lukasmartinelli** [comment]
btw (doesn't fit into this ticket).

can you add yourself to https://github.com/maputnik/editor/blob/master/LICENSE and the README license. I think it makes sense to add you as contributor regarding copyright. if you want to
couldn't find your full name :)

**Comment by orangemug** [comment]
@lukasmartinelli just a note, there is no need for the high res image version anymore as I have redone the logo in SVG and created a repo, see <https://github.com/orangemug/maputnik-design> (I'll transfer over the repo shortly)

**Comment by orangemug** [comment]
Moved the repo over to https://github.com/maputnik/design

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli just a note, there is no need for the high res image version anymore as I have redone the logo in SVG and created a repo, see https://github.com/orangemug/maputnik-design (I'll transfer over the repo shortly)

This is so crazy. I tried to make a SVG logo and failed miserably. This is so gorgeous how you recreated it (should have used that for the laptop stickers). There is even an animated version :love_letter: 

designer and dev :astonished: 

@orangemug you keep surprising me.
Everyone else: check out https://github.com/maputnik/design

Love it! Keep going.

**Comment by orangemug** [comment]
Finally found the time to merge the PR. Closing the issue

See the new website at <http://maputnik.com/>

**Comment by lukasmartinelli** [comment]
Very nice 🙇
