### ISSUE TITLE
Update description

### ISSUE THREAD

**Issue by pathmapper** [maputnik/maputnik.github.io#12]
Currently it states:
![description](https://user-images.githubusercontent.com/20856381/44373695-cb9a7500-a4ea-11e8-9368-8e7ccfe1e35b.png)

> Maputnik is a free visual style editor **for maps** targeted at developers and designers.

Add at least that Maputnik is a visual style editor for the Mapbox style specification and maybe link to the spec.

Ref: https://github.com/maputnik/editor/issues/361#issuecomment-414454803

> We need to get better at explaining what Maputnik is

**Comment by orangemug** [comment]
@pathmapper what do you think about

Website tagline:
> Maputnik is an open source visual editor for the [Mapbox Style Specification](https://www.mapbox.com/mapbox-gl-js/style-spec)

Repo tagline:
> An open source visual editor for the 'Mapbox Style Specification'

Thoughts?

**Comment by pathmapper** [comment]
@orangemug sounds good to me.

There is a disclaimer for the repo https://github.com/maputnik/editor#license : 

> **Disclaimer** This project is not affiliated with Mapbox or Mapbox Studio. It is a independent style editor for the open source technology in the Mapbox GL ecosystem. As contributor please take extra care of not violating any Mapbox trademarks. Do not get inspired by Mapbox Studio and make your own decisions for a good style editor.

What about adding the first and perhaps also the second sentence to the Website? 

Using the word _Mapbox_ it should be clear that there is no affiliation to the company with the same name.

Website tagline:

> Maputnik is an open source visual editor for the [Mapbox Style Specification](https://www.mapbox.com/mapbox-gl-js/style-spec)*

Website footer:
> ***Disclaimer** This project is not affiliated with Mapbox or Mapbox Studio.

or

> ***Disclaimer** This project is not affiliated with Mapbox or Mapbox Studio. It is a independent style editor for the open source technology in the Mapbox GL ecosystem.

**Comment by orangemug** [comment]
Seems like a good idea to me. I like option 2 for the footer

> ***Disclaimer** This project is not affiliated with Mapbox or Mapbox Studio. It is a independent style editor for the open source technology in the Mapbox GL ecosystem.

**Comment by orangemug** [comment]
Closed by #13
